### ISSUE TITLE
Project does not build inside IDEA with current compiler and tools

### ISSUE THREAD

**Issue by mel4tonin4** [wojta/kotlin-nodejs-experiment#1]
Hello.

This project does not build anymore inside IDEA with Kotlin 1.1.

I'm attaching an updated version that builds.
[kotlin-nodejs-experiment.zip](https://github.com/wojta/kotlin-nodejs-experiment/files/851406/kotlin-nodejs-experiment.zip)

People from JetBrains helped me to update it.

Thanks.

**Comment by wojta** [comment]
Hi @mel4tonin4 ,

thank you for that. 
I don't understand the point of that `apply plugin: 'kotlin-platform-js'`. I think that it's something to help with having JVM and JS code share common code base. It is probably not necessary here. But It would help me greately with https://github.com/wojta/hello-kotlin. 
I'll update both repositories soon to work with Kotlin 1.1.x.

**Comment by mel4tonin4** [comment]
These are the instructions that I received (from a JetBrains developer on the Kotlin slack, #javascript channel) regarding that plugin:

> you can also add `apply plugin: 'kotlin-platform-js'` to your js subproject
> This will override platform auto-detection by stdlib dependency

Hope it helps.

**Comment by wojta** [comment]
I updated this project to Kotlin 1.1.
